export const product = [
  //id	nameProduct	price	description	rate	idBrand
  {
    id: '1',
    name: 'apple watch n1',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '2',
    name: 'apple watch n2',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '3',
    name: 'apple watch n3',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '4',
    name: 'apple watch n4',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '5',
    name: 'apple watch n5',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '6',
    name: 'apple watch n6',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '7',
    name: 'apple watch n7',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '8',
    name: 'apple watch n8',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 1,
  },
  {
    id: '9',
    name: 'apple watch n9',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '10',
    name: 'apple watch n10',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '11',
    name: 'apple watch n11',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '12',
    name: 'apple watch n13',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '13',
    name: 'apple watch n13',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '14',
    name: 'apple watch n14',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '15',
    name: 'apple watch n15',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '16',
    name: 'apple watch n16',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 2,
  },
  {
    id: '17',
    name: 'apple watch n17',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '18',
    name: 'apple watch n8',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '19',
    name: 'apple watch n19',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '20',
    name: 'apple watch n20',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '21',
    name: 'apple watch n21',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '22',
    name: 'apple watch n22',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '23',
    name: 'apple watch n23',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
  {
    id: '24',
    name: 'apple watch n24',
    price: 2500000,
    description: 'veryGood',
    rate: 5,
    idBrand: 3,
  },
];
